import { FAQItem, Milestone, Announcement, Team, Notification } from "@/types";

export const INITIAL_FAQS: FAQItem[] = [
  {
    id: "faq-1",
    question: "Who can participate in the AI Lab Hackathon?",
    answer: "Any undergraduate or postgraduate student currently enrolled in engineering, technology, or science courses is eligible to participate. Cross-department teams are highly encouraged!",
    category: "General",
  },
  {
    id: "faq-2",
    question: "What is the maximum team size?",
    answer: "Teams must consist of 2 to 4 members. Single-member registrations are not permitted for this hackathon.",
    category: "Registration",
  },
  {
    id: "faq-3",
    question: "Are there any specific themes or tracks?",
    answer: "The primary focus is on AI and Machine Learning. Specific tracks include: Generative AI for Education, AI in Healthcare, Smart Campus Solutions, and Decentralized AI Agents.",
    category: "Technical",
  },
  {
    id: "faq-4",
    question: "What are the prizes for the winners?",
    answer: "The cash prize pool is ₹1,00,000, with ₹50,000 for the Winner, ₹30,000 for the Runner-Up, and ₹20,000 for the Best Innovative AI Agent. All participants receive AI Lab certificates and cloud GPU credits.",
    category: "Prizes",
  },
  {
    id: "faq-5",
    question: "Will the event be physical or virtual?",
    answer: "The final 24-hour coding sprint and pitching will take place physically in the main AI Research Lab. Early rounds (ideas submission) will be submitted online.",
    category: "General",
  },
];

export const INITIAL_MILESTONES: Milestone[] = [
  {
    id: "m-1",
    title: "Registration Opens",
    description: "Submit team details and department verification.",
    date: "June 25, 2026",
    status: "completed",
  },
  {
    id: "m-2",
    title: "Idea Abstract Submission",
    description: "Submit a 2-page PDF explaining your AI solution architecture.",
    date: "July 05, 2026",
    status: "ongoing",
  },
  {
    id: "m-3",
    title: "Shortlist Announcement",
    description: "Top 20 teams selected based on feasibility and innovation.",
    date: "July 12, 2026",
    status: "upcoming",
  },
  {
    id: "m-4",
    title: "24-Hour Coding Sprint",
    description: "Mentoring sessions and physical hacking in the College AI Lab.",
    date: "July 18, 2026",
    status: "upcoming",
  },
  {
    id: "m-5",
    title: "Final Pitch & Demo",
    description: "Present prototypes to industry judges and winners announced.",
    date: "July 19, 2026",
    status: "upcoming",
  },
];

export const INITIAL_ANNOUNCEMENTS: Announcement[] = [
  {
    id: "ann-1",
    title: "Idea Templates Released!",
    content: "Make sure to download the idea submission slide deck template from the resources tab. The submission deadline is July 5th, 11:59 PM.",
    type: "info",
    date: "1 hour ago",
  },
  {
    id: "ann-2",
    title: "Cloud GPU Credits Available",
    content: "All approved teams can now claim ₹5,000 worth of Nebius/RunPod credits inside their participant dashboards.",
    type: "success",
    date: "1 day ago",
  },
  {
    id: "ann-3",
    title: "Update Team Member Details",
    content: "Ensure all register numbers are accurate. System profiles will be verified against the college register on July 2nd.",
    type: "warning",
    date: "3 days ago",
  },
];

export const INITIAL_NOTIFICATIONS: Notification[] = [
  {
    id: "notif-1",
    type: "approval",
    title: "Team Registration Approved",
    body: "Your team Neural Knights has been approved by the organizers. You can now access all platform features.",
    read: false,
    priority: "high",
    createdAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    relatedTeamId: "team-1",
  },
  {
    id: "notif-2",
    type: "judge",
    title: "New Evaluation Received",
    body: "Judge has submitted an evaluation for your project. Innovation: 8/10. Check the Project tab for full feedback.",
    read: false,
    priority: "normal",
    createdAt: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
    relatedTeamId: "team-1",
  },
  {
    id: "notif-3",
    type: "system",
    title: "Platform Update",
    body: "New resources have been added to the Resources hub. Check out the latest AI APIs and datasets.",
    read: false,
    priority: "normal",
    createdAt: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
    relatedTeamId: "team-1",
  },
  {
    id: "notif-4",
    type: "deadline",
    title: "Idea Submission Deadline — 5 Days",
    body: "Your idea abstract is due on July 5, 2026 at 11:59 PM. Submit your 2-page PDF from the Project tab.",
    read: true,
    priority: "high",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString(),
  },
  {
    id: "notif-5",
    type: "action",
    title: "Profile Audit Pending",
    body: "Your team profile audit is pending review. The organizers will verify your department credentials soon.",
    read: true,
    priority: "high",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 6).toISOString(),
    relatedTeamId: "team-1",
  },
  {
    id: "notif-6",
    type: "system",
    title: "Platform Maintenance — Tonight 11 PM",
    body: "The platform will undergo scheduled maintenance tonight from 11 PM to 1 AM. Save your work before then.",
    read: true,
    priority: "normal",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 12).toISOString(),
  },
  {
    id: "notif-7",
    type: "system",
    title: "GPU Credits Unlocked",
    body: "₹5,000 in Nebius GPU credits have been credited to your team account. Access from the Project tab.",
    read: true,
    priority: "normal",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    relatedTeamId: "team-1",
  },
  {
    id: "notif-8",
    type: "deadline",
    title: "Member Details Verification — July 2",
    body: "All member register numbers will be cross-verified with college records on July 2. Ensure accuracy.",
    read: true,
    priority: "normal",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
  },
];

export const INITIAL_TEAMS: Team[] = [
  {
    id: "team-1",
    name: "Neural Knights",
    size: 3,
    status: "APPROVED",
    createdAt: "2026-06-25T14:32:00.000Z",
    projectDescription: "Developing a real-time localized RAG system for campus academic advisory.",
    qrToken: "NK-AI26-104-SEC7F3A",
    problemStatementId: "ps-1",
    paymentVerified: false,

    ideaSubmitted: false,
    shortlisted: false,
    githubUrl: "https://github.com/abhishek-sharma/advisory-rag",
    videoUrl: "https://youtube.com/watch?v=advisory-rag-demo",
    demoUrl: "https://advisory-rag.siet.edu",
    aiDisclosure: "We used Claude 3.5 Sonnet for drafting system models.",
    submitted: true,
    submittedAt: new Date().toISOString(),
    attendance: { teamId: "team-1", checkedIn: false },
    members: [
      {
        name: "Abhishek Sharma",
        registerNumber: "2022CSE0101",
        email: "abhishek@college.edu",
        phone: "9876543210",
        department: "Computer Science & Engineering",
        year: "3rd Year",
        skills: ["React", "Python", "LangChain", "FastAPI"],
        github: "github.com/abhishek-sharma",
        isLeader: true,
      },
      {
        name: "Neha Patel",
        registerNumber: "2022CSE0145",
        email: "neha@college.edu",
        phone: "9876543211",
        department: "Computer Science & Engineering",
        year: "3rd Year",
        skills: ["TailwindCSS", "Next.js", "TypeScript"],
        github: "github.com/neha-patel",
      },
      {
        name: "Rahul Verma",
        registerNumber: "2022ECE0092",
        email: "rahul@college.edu",
        phone: "9876543212",
        department: "Electronics & Communication",
        year: "3rd Year",
        skills: ["PyTorch", "Data Science", "PostgreSQL"],
      },
    ],
    milestonesProgress: [
      { id: "ms-1", title: "Ideation & Design Diagram", completed: true },
      { id: "ms-2", title: "Database & API Schema Setup", completed: true },
      { id: "ms-3", title: "Core ML/AI Model Integration", completed: true },
      { id: "ms-4", title: "Frontend Dashboard Integration", completed: false },
      { id: "ms-5", title: "Public Deployment & Pitch slides", completed: false },
    ],
    evaluations: [
      {
        innovation: 8,
        feasibility: 9,
        presentation: 8,
        technicalDepth: 8,
        aiUsage: 9,
        feedback: "Great localized RAG system, UI is highly responsive.",
        judgeEmail: "judge@college.edu",
      },
    ],
    supportTickets: [],
  },
  {
    id: "team-2",
    name: "Visionary Minds",
    size: 2,
    status: "PENDING",
    createdAt: "2026-06-26T09:15:00.000Z",
    projectDescription: "AI-powered computer vision system detecting safety violations in student labs.",
    qrToken: "VM-AI26-105-SEC8B2C",
    problemStatementId: "ps-2",
    paymentVerified: true,

    ideaSubmitted: false,
    shortlisted: false,
    attendance: { teamId: "team-2", checkedIn: false },
    members: [
      {
        name: "Siddharth Sen",
        registerNumber: "2023AI0021",
        email: "sid@college.edu",
        phone: "9123456780",
        department: "Artificial Intelligence and Data Science",
        year: "2nd Year",
        skills: ["OpenCV", "YOLOv8", "Python", "Flask"],
        github: "github.com/sidsen",
        isLeader: true,
      },
      {
        name: "Priya Roy",
        registerNumber: "2023AI0008",
        email: "priya@college.edu",
        phone: "9123456781",
        department: "Artificial Intelligence and Data Science",
        year: "2nd Year",
        skills: ["React Native", "TailwindCSS", "Framer Motion"],
      },
    ],
    milestonesProgress: [
      { id: "ms-1", title: "Ideation & Design Diagram", completed: true },
      { id: "ms-2", title: "Database & API Schema Setup", completed: false },
      { id: "ms-3", title: "Core ML/AI Model Integration", completed: false },
      { id: "ms-4", title: "Frontend Dashboard Integration", completed: false },
      { id: "ms-5", title: "Public Deployment & Pitch slides", completed: false },
    ],
    evaluations: [],
    supportTickets: [],
  },
  {
    id: "team-3",
    name: "Cyber Sentinels",
    size: 4,
    status: "PENDING",
    createdAt: "2026-06-26T10:45:00.000Z",
    projectDescription: "Intrusion detection dashboard using federated learning across campus nodes.",
    qrToken: "CS-AI26-106-SECD9E1",
    problemStatementId: "ps-3",
    paymentVerified: false,

    ideaSubmitted: false,
    shortlisted: false,
    attendance: { teamId: "team-3", checkedIn: false },
    members: [
      {
        name: "Vikram Malhotra",
        registerNumber: "2021CSE0004",
        email: "vikram@college.edu",
        phone: "9234567890",
        department: "Computer Science & Engineering",
        year: "4th Year",
        skills: ["Kubernetes", "Docker", "Go", "TensorFlow"],
        github: "github.com/vikramm",
        isLeader: true,
      },
      {
        name: "Anjali Gupta",
        registerNumber: "2021CSE0088",
        email: "anjali@college.edu",
        phone: "9234567891",
        department: "Computer Science & Engineering",
        year: "4th Year",
        skills: ["Cyber Security", "Linux", "Node.js"],
      },
      {
        name: "Dev Dixit",
        registerNumber: "2021ECE0202",
        email: "dev@college.edu",
        phone: "9234567892",
        department: "Electronics & Communication",
        year: "4th Year",
        skills: ["IoT", "Raspberry Pi", "C++"],
      },
      {
        name: "Riya Seth",
        registerNumber: "2021IT0045",
        email: "riya@college.edu",
        phone: "9234567893",
        department: "Information Technology",
        year: "4th Year",
        skills: ["Python", "SQL", "Tableau"],
      },
    ],
    milestonesProgress: [
      { id: "ms-1", title: "Ideation & Design Diagram", completed: true },
      { id: "ms-2", title: "Database & API Schema Setup", completed: false },
      { id: "ms-3", title: "Core ML/AI Model Integration", completed: false },
      { id: "ms-4", title: "Frontend Dashboard Integration", completed: false },
      { id: "ms-5", title: "Public Deployment & Pitch slides", completed: false },
    ],
    evaluations: [],
    supportTickets: [],
  },
  {
    id: "team-4",
    name: "BioSynth Agents",
    size: 2,
    status: "REJECTED",
    createdAt: "2026-06-24T08:12:00.000Z",
    projectDescription: "Predicting molecular docking combinations for pharmaceutical chemistry laboratory datasets.",
    qrToken: "BA-AI26-107-SECA5F2",
    problemStatementId: "ps-4",
    paymentVerified: true,

    ideaSubmitted: true,
    shortlisted: false,
    attendance: { teamId: "team-4", checkedIn: false },
    members: [
      {
        name: "Amit Banerjee",
        registerNumber: "2022BI0012",
        email: "amit@college.edu",
        phone: "9345678901",
        department: "Biotechnology",
        year: "3rd Year",
        skills: ["Bioinformatics", "Python", "R"],
        github: "github.com/amit-bio",
        isLeader: true,
      },
      {
        name: "Karan Johar",
        registerNumber: "2022CSE0212",
        email: "karan@college.edu",
        phone: "9345678902",
        department: "Computer Science & Engineering",
        year: "3rd Year",
        skills: ["Python", "Scikit-Learn", "FastAPI"],
      },
    ],
    milestonesProgress: [
      { id: "ms-1", title: "Ideation & Design Diagram", completed: true },
      { id: "ms-2", title: "Database & API Schema Setup", completed: true },
      { id: "ms-3", title: "Core ML/AI Model Integration", completed: false },
      { id: "ms-4", title: "Frontend Dashboard Integration", completed: false },
      { id: "ms-5", title: "Public Deployment & Pitch slides", completed: false },
    ],
    evaluations: [],
    supportTickets: [],
  },
];

export const INITIAL_VOLUNTEERS = [
  {
    id: "vol-1",
    name: "Riya Sharma",
    phone: "9876543219",
    email: "riya@college.edu",
    assignedArea: "Lab 3 (AI Research Lab)",
    assignedResponsibilities: "Network & Power stability support",
    createdAt: new Date().toISOString(),
  }
];
