import { FAQItem, Milestone, Announcement, Team } from "@/types";

export const INITIAL_FAQS: FAQItem[] = [
  {
    id: "faq-1",
    question: "Who can participate in the AI Lab Hackathon?",
    answer: "Any undergraduate or postgraduate student currently enrolled in engineering, technology, or science courses is eligible to participate. Cross-department teams are highly encouraged!",
    category: "General",
  },
  {
    id: "faq-2",
    question: "What is the maximum team size?",
    answer: "Teams must consist of 2 to 4 members. Single-member registrations are not permitted for this hackathon.",
    category: "Registration",
  },
  {
    id: "faq-3",
    question: "Are there any specific themes or tracks?",
    answer: "The primary focus is on AI and Machine Learning. Specific tracks include: Generative AI for Education, AI in Healthcare, Smart Campus Solutions, and Decentralized AI Agents.",
    category: "Technical",
  },
  {
    id: "faq-4",
    question: "What are the prizes for the winners?",
    answer: "The cash prize pool is ₹1,00,000, with ₹50,000 for the Winner, ₹30,000 for the Runner-Up, and ₹20,000 for the Best Innovative AI Agent. All participants receive AI Lab certificates and cloud GPU credits.",
    category: "Prizes",
  },
  {
    id: "faq-5",
    question: "Will the event be physical or virtual?",
    answer: "The final 24-hour coding sprint and pitching will take place physically in the main AI Research Lab. Early rounds (ideas submission) will be submitted online.",
    category: "General",
  },
];

export const INITIAL_MILESTONES: Milestone[] = [
  {
    id: "m-1",
    title: "Registration Opens",
    description: "Submit team details and department verification.",
    date: "June 25, 2026",
    status: "completed",
  },
  {
    id: "m-2",
    title: "Idea Abstract Submission",
    description: "Submit a 2-page PDF explaining your AI solution architecture.",
    date: "July 05, 2026",
    status: "ongoing",
  },
  {
    id: "m-3",
    title: "Shortlist Announcement",
    description: "Top 20 teams selected based on feasibility and innovation.",
    date: "July 12, 2026",
    status: "upcoming",
  },
  {
    id: "m-4",
    title: "24-Hour Coding Sprint",
    description: "Mentoring sessions and physical hacking in the College AI Lab.",
    date: "July 18, 2026",
    status: "upcoming",
  },
  {
    id: "m-5",
    title: "Final Pitch & Demo",
    description: "Present prototypes to industry judges and winners announced.",
    date: "July 19, 2026",
    status: "upcoming",
  },
];

export const INITIAL_ANNOUNCEMENTS: Announcement[] = [
  {
    id: "ann-1",
    title: "Idea Templates Released!",
    content: "Make sure to download the idea submission slide deck template from the resources tab. The submission deadline is July 5th, 11:59 PM.",
    type: "info",
    date: "1 hour ago",
  },
  {
    id: "ann-2",
    title: "Cloud GPU Credits Available",
    content: "All approved teams can now claim ₹5,000 worth of Nebius/RunPod credits inside their participant dashboards.",
    type: "success",
    date: "1 day ago",
  },
  {
    id: "ann-3",
    title: "Update Team Member Details",
    content: "Ensure all register numbers are accurate. System profiles will be verified against the college register on July 2nd.",
    type: "warning",
    date: "3 days ago",
  },
];

export const INITIAL_TEAMS: Team[] = [
  {
    id: "team-1",
    name: "Neural Knights",
    size: 3,
    status: "APPROVED",
    createdAt: "2026-06-25T14:32:00.000Z",
    projectDescription: "Developing a real-time localized RAG system for campus academic advisory.",
    members: [
      {
        name: "Abhishek Sharma",
        registerNumber: "2022CSE0101",
        email: "abhishek@college.edu",
        phone: "9876543210",
        department: "Computer Science & Engineering",
        year: "3rd Year",
        skills: ["React", "Python", "LangChain", "FastAPI"],
        github: "github.com/abhishek-sharma",
        isLeader: true,
      },
      {
        name: "Neha Patel",
        registerNumber: "2022CSE0145",
        email: "neha@college.edu",
        phone: "9876543211",
        department: "Computer Science & Engineering",
        year: "3rd Year",
        skills: ["TailwindCSS", "Next.js", "TypeScript"],
        github: "github.com/neha-patel",
      },
      {
        name: "Rahul Verma",
        registerNumber: "2022ECE0092",
        email: "rahul@college.edu",
        phone: "9876543212",
        department: "Electronics & Communication",
        year: "3rd Year",
        skills: ["PyTorch", "Data Science", "PostgreSQL"],
      },
    ],
  },
  {
    id: "team-2",
    name: "Visionary Minds",
    size: 2,
    status: "PENDING",
    createdAt: "2026-06-26T09:15:00.000Z",
    projectDescription: "AI-powered computer vision system detecting safety violations in student labs.",
    members: [
      {
        name: "Siddharth Sen",
        registerNumber: "2023AI0021",
        email: "sid@college.edu",
        phone: "9123456780",
        department: "Artificial Intelligence & Data Science",
        year: "2nd Year",
        skills: ["OpenCV", "YOLOv8", "Python", "Flask"],
        github: "github.com/sidsen",
        isLeader: true,
      },
      {
        name: "Priya Roy",
        registerNumber: "2023AI0008",
        email: "priya@college.edu",
        phone: "9123456781",
        department: "Artificial Intelligence & Data Science",
        year: "2nd Year",
        skills: ["React Native", "TailwindCSS", "Framer Motion"],
      },
    ],
  },
  {
    id: "team-3",
    name: "Cyber Sentinels",
    size: 4,
    status: "PENDING",
    createdAt: "2026-06-26T10:45:00.000Z",
    projectDescription: "Intrusion detection dashboard using federated learning across campus nodes.",
    members: [
      {
        name: "Vikram Malhotra",
        registerNumber: "2021CSE0004",
        email: "vikram@college.edu",
        phone: "9234567890",
        department: "Computer Science & Engineering",
        year: "4th Year",
        skills: ["Kubernetes", "Docker", "Go", "TensorFlow"],
        github: "github.com/vikramm",
        isLeader: true,
      },
      {
        name: "Anjali Gupta",
        registerNumber: "2021CSE0088",
        email: "anjali@college.edu",
        phone: "9234567891",
        department: "Computer Science & Engineering",
        year: "4th Year",
        skills: ["Cyber Security", "Linux", "Node.js"],
      },
      {
        name: "Dev Dixit",
        registerNumber: "2021ECE0202",
        email: "dev@college.edu",
        phone: "9234567892",
        department: "Electronics & Communication",
        year: "4th Year",
        skills: ["IoT", "Raspberry Pi", "C++"],
      },
      {
        name: "Riya Seth",
        registerNumber: "2021IT0045",
        email: "riya@college.edu",
        phone: "9234567893",
        department: "Information Technology",
        year: "4th Year",
        skills: ["Python", "SQL", "Tableau"],
      },
    ],
  },
  {
    id: "team-4",
    name: "BioSynth Agents",
    size: 2,
    status: "REJECTED",
    createdAt: "2026-06-24T08:12:00.000Z",
    projectDescription: "Predicting molecular docking combinations for pharmaceutical chemistry laboratory datasets.",
    members: [
      {
        name: "Amit Banerjee",
        registerNumber: "2022BI0012",
        email: "amit@college.edu",
        phone: "9345678901",
        department: "Biotechnology",
        year: "3rd Year",
        skills: ["Bioinformatics", "Python", "R"],
        github: "github.com/amit-bio",
        isLeader: true,
      },
      {
        name: "Karan Johar",
        registerNumber: "2022CSE0212",
        email: "karan@college.edu",
        phone: "9345678902",
        department: "Computer Science & Engineering",
        year: "3rd Year",
        skills: ["Python", "Scikit-Learn", "FastAPI"],
      },
    ],
  },
];
